// <auto-generated />
namespace ContosoUniversity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addmorecolumnintablesnhatkyvanhanh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmorecolumnintablesnhatkyvanhanh));
        
        string IMigrationMetadata.Id
        {
            get { return "202205260312445_add-more-column-in-tables-nhat-ky-van-hanh"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
